apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-interceptor
spec:
  serviceType: LoadBalancer
  triggers:
  - name: chatbot-trig
    interceptor:
      github:
        secretRef:
          secretName: github-shared-secret
          secretKey: token
          namespace: default
        eventTypes:
        - issue_comment
    bindings:
      - name: chatbot-binding
    template:
      name: chatbot-template